import { Inter } from "next/font/google";
import "./globals.css";
import MainNavigation from "@/components/navigation/MainNavigation";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div>
          <MainNavigation />
          {children}
        </div>
      </body>
    </html>
  );
}
