export const courseData = [
  {
    courseName: "Introduction to Programing",
    instructor: "Abhishek Patil",
    description:
      "Programming involves writing code to instruct computers to perform tasks. It enhances problem-solving skills and creativity, enabling the creation of software, websites, and apps. Essential in today’s tech-driven world, programming offers endless innovation and career opportunities. Start coding to unlock technology’s potential and bring your ideas to life!",
    courseId: "course1",
    courseImg:
      "https://img.freepik.com/free-photo/medium-shot-girl-holding-clipboard_23-2148888878.jpg?size=626&ext=jpg&ga=GA1.1.77852075.1725111883&semt=ais_hybrid",
    isEnrolled: false,
    progress: 0,
    lectures: [
      {
        lectureId: "lec1",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Introduction to APIs",
        isCompleted: false,
      },
      {
        lectureId: "lec2",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Understanding RESTful APIs",
        isCompleted: false,
      },
      {
        lectureId: "lec3",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "API Authentication and Authorization",
        isCompleted: false,
      },
      {
        lectureId: "lec4",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Building Your First API",
        isCompleted: false,
      },
      {
        lectureId: "lec5",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "API Documentation with Swagger",
        isCompleted: false,
      },
      {
        lectureId: "lec6",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Error Handling in APIs",
        isCompleted: false,
      },
      {
        lectureId: "lec7",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Versioning Your API",
        isCompleted: false,
      },
      {
        lectureId: "lec8",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "API Rate Limiting and Throttling",
        isCompleted: false,
      },
      {
        lectureId: "lec9",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Testing and Debugging APIs",
        isCompleted: false,
      },
      {
        lectureId: "lec10",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Best Practices for API Design",
        isCompleted: false,
      },
    ],
  },
  {
    courseName: "Introduction to Computer Networking",
    instructor: "Akshay",
    description:
      "Computer Networking involves connecting multiple computers and devices to share resources and information. This course covers the fundamentals of networking, including network topologies, protocols, and security. By understanding networking, you can design and manage efficient and secure networks, essential for modern communication and data exchange.",
    courseId: "course2",
    courseImg:
      "https://img.freepik.com/free-vector/female-student-listening-webinar-online_74855-6461.jpg?size=626&ext=jpg&ga=GA1.1.77852075.1725111883&semt=ais_hybrid",
    isEnrolled: false,
    progress: 0,
    lectures: [
      {
        lectureId: "lec1",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Introduction to Computer Networking",
        isCompleted: false,
      },
      {
        lectureId: "lec2",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Network Topologies and Types",
        isCompleted: false,
      },
      {
        lectureId: "lec3",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "OSI and TCP/IP Models",
        isCompleted: false,
      },
      {
        lectureId: "lec4",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "IP Addressing and Subnetting",
        isCompleted: false,
      },
      {
        lectureId: "lec5",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Routing and Switching",
        isCompleted: false,
      },
      {
        lectureId: "lec6",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Network Protocols and Services",
        isCompleted: false,
      },
      {
        lectureId: "lec7",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Wireless Networking",
        isCompleted: false,
      },
      {
        lectureId: "lec8",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Network Security Basics",
        isCompleted: false,
      },
      {
        lectureId: "lec9",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Troubleshooting and Maintenance",
        isCompleted: false,
      },
      {
        lectureId: "lec10",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Future Trends in Networking",
        isCompleted: false,
      },
    ],
  },
  {
    courseName: "Introduction to Database Management Systems",
    instructor: "Vaibhav",
    description:
      "A Database Management System (DBMS) is software that allows you to create, manage, and manipulate databases efficiently. This course covers the fundamentals of DBMS, including data models, SQL, normalization, and database design. Understanding DBMS is crucial for managing data in various applications, ensuring data integrity, and optimizing performance.",
    courseId: "course3",
    courseImg:
      "https://img.freepik.com/free-vector/online-education-landing-page-template_23-2149046832.jpg?size=626&ext=jpg&ga=GA1.1.77852075.1725111883&semt=ais_hybrid",
    isEnrolled: false,
    progress: 0,
    lectures: [
      {
        lectureId: "lec1",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Introduction to DBMS",
        isCompleted: false,
      },
      {
        lectureId: "lec2",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Data Models and Schemas",
        isCompleted: false,
      },
      {
        lectureId: "lec3",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Entity-Relationship Model",
        isCompleted: false,
      },
      {
        lectureId: "lec4",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Relational Model and SQL",
        isCompleted: false,
      },
      {
        lectureId: "lec5",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Normalization and Database Design",
        isCompleted: false,
      },
      {
        lectureId: "lec6",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Transactions and Concurrency Control",
        isCompleted: false,
      },
      {
        lectureId: "lec7",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Indexing and Query Optimization",
        isCompleted: false,
      },
      {
        lectureId: "lec8",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Database Security",
        isCompleted: false,
      },
      {
        lectureId: "lec9",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "NoSQL Databases",
        isCompleted: false,
      },
      {
        lectureId: "lec10",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Future Trends in Database Management",
        isCompleted: false,
      },
    ],
  },
  {
    courseName: "Software Engineering",
    instructor: "Vishal",
    description:
      "This course covers the principles and practices of software engineering, including software development life cycle, methodologies, and project management. It prepares students to design, develop, and maintain high-quality software systems.",
    courseId: "course4",
    courseImg:
      "https://img.freepik.com/free-vector/catalog-online-courses-isometric-icon-online-education-internet-learning_39422-1021.jpg?size=626&ext=jpg&ga=GA1.1.77852075.1725111883&semt=ais_hybrid",
    isEnrolled: false,
    progress: 0,
    lectures: [
      {
        lectureId: "lec1",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Introduction to Software Engineering",
        isCompleted: false,
      },
      {
        lectureId: "lec2",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Software Development Life Cycle",
        isCompleted: false,
      },
      {
        lectureId: "lec3",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Agile Methodologies",
        isCompleted: false,
      },
      {
        lectureId: "lec4",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Requirements Engineering",
        isCompleted: false,
      },
      {
        lectureId: "lec5",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Software Design",
        isCompleted: false,
      },
      {
        lectureId: "lec6",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Software Testing",
        isCompleted: false,
      },
      {
        lectureId: "lec7",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Project Management",
        isCompleted: false,
      },
      {
        lectureId: "lec8",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Software Maintenance",
        isCompleted: false,
      },
      {
        lectureId: "lec9",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "DevOps and Continuous Integration",
        isCompleted: false,
      },
      {
        lectureId: "lec10",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Future Trends in Software Engineering",
        isCompleted: false,
      },
    ],
  },
  {
    courseName: "Data Structures and Algorithms",
    instructor: "Prashant",
    description:
      "This course covers the fundamental concepts of data structures and algorithms, including arrays, linked lists, trees, and sorting algorithms. Mastering DSA is essential for writing efficient code and solving complex problems, making it a core skill for any computer scientist.",
    courseId: "course5",
    courseImg:
      "https://img.freepik.com/free-vector/online-education-website-page-design_98292-8324.jpg?size=626&ext=jpg&ga=GA1.1.77852075.1725111883&semt=ais_hybrid",
    isEnrolled: false,
    progress: 0,
    lectures: [
      {
        lectureId: "lec1",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Introduction to Data Structures and Algorithms",
        isCompleted: false,
      },
      {
        lectureId: "lec2",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Arrays and Linked Lists",
        isCompleted: false,
      },
      {
        lectureId: "lec3",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Stacks and Queues",
        isCompleted: false,
      },
      {
        lectureId: "lec4",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Trees and Graphs",
        isCompleted: false,
      },
      {
        lectureId: "lec5",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Sorting Algorithms",
        isCompleted: false,
      },
      {
        lectureId: "lec6",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Searching Algorithms",
        isCompleted: false,
      },
      {
        lectureId: "lec7",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Dynamic Programming",
        isCompleted: false,
      },
      {
        lectureId: "lec8",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Greedy Algorithms",
        isCompleted: false,
      },
      {
        lectureId: "lec9",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Graph Algorithms",
        isCompleted: false,
      },
      {
        lectureId: "lec10",
        url: "https://youtu.be/0BIaDVnYp2A?si=vQA82msVLVj6AG_L",
        title: "Advanced Topics in DSA",
        isCompleted: false,
      },
    ],
  },
  {
    courseName: "Operating Systems",
    instructor: "Govind",
    description:
      "This course provides an in-depth understanding of operating systems, including process management, memory management, and file systems. Knowledge of operating systems is crucial for managing computer resources and ensuring efficient system performance.",
    courseId: "course6",
    courseImg:
      "https://img.freepik.com/free-vector/online-learning-landing-page-design_23-2149058253.jpg?size=626&ext=jpg&ga=GA1.1.77852075.1725111883&semt=ais_hybrid",
    isEnrolled: false,
    progress: 0,
    lectures: [
      {
        lectureId: "lec1",
        url: "https://youtu.be/y3OOaXrFy-Q?si=bVDNypIZdtIAyun1",
        title: "Introduction to Operating Systems",
        isCompleted: false,
      },
      {
        lectureId: "lec2",
        url: "https://youtu.be/y3OOaXrFy-Q?si=bVDNypIZdtIAyun1",
        title: "Process Management",
        isCompleted: false,
      },
      {
        lectureId: "lec3",
        url: "https://youtu.be/y3OOaXrFy-Q?si=bVDNypIZdtIAyun1",
        title: "Memory Management",
        isCompleted: false,
      },
      {
        lectureId: "lec4",
        url: "https://youtu.be/y3OOaXrFy-Q?si=bVDNypIZdtIAyun1",
        title: "File Systems",
        isCompleted: false,
      },
      {
        lectureId: "lec5",
        url: "https://youtu.be/y3OOaXrFy-Q?si=bVDNypIZdtIAyun1",
        title: "Concurrency",
        isCompleted: false,
      },
      {
        lectureId: "lec6",
        url: "https://youtu.be/y3OOaXrFy-Q?si=bVDNypIZdtIAyun1",
        title: "Scheduling",
        isCompleted: false,
      },
      {
        lectureId: "lec7",
        url: "https://youtu.be/y3OOaXrFy-Q?si=bVDNypIZdtIAyun1",
        title: "Virtual Memory",
        isCompleted: false,
      },
      {
        lectureId: "lec8",
        url: "https://youtu.be/y3OOaXrFy-Q?si=bVDNypIZdtIAyun1",
        title: "Security and Protection",
        isCompleted: false,
      },
      {
        lectureId: "lec9",
        url: "https://youtu.be/y3OOaXrFy-Q?si=bVDNypIZdtIAyun1",
        title: "Distributed Systems",
        isCompleted: false,
      },
      {
        lectureId: "lec10",
        url: "https://youtu.be/y3OOaXrFy-Q?si=bVDNypIZdtIAyun1",
        title: "Advanced Topics in Operating Systems",
        isCompleted: false,
      },
    ],
  },
  {
    courseName: "Introduction to DevOps",
    instructor: "Yash",
    description:
      "This course covers the essential principles and practices of DevOps, including continuous integration, continuous delivery, and infrastructure as code. By understanding DevOps, you can improve collaboration between development and operations teams, automate workflows, and deliver software more efficiently.",
    courseId: "course7",
    courseImg:
      "https://img.freepik.com/free-vector/online-education-landing-page-design_23-2149058668.jpg?size=626&ext=jpg&ga=GA1.1.77852075.1725111883&semt=ais_hybrid",
    isEnrolled: false,
    progress: 0,
    lectures: [
      {
        lectureId: "lec1",
        url: "https://youtu.be/y3OOaXrFy-Q?si=bVDNypIZdtIAyun1",
        title: "Introduction to DevOps",
        isCompleted: false,
      },
      {
        lectureId: "lec2",
        url: "https://youtu.be/y3OOaXrFy-Q?si=bVDNypIZdtIAyun1",
        title: "DevOps Principles and Culture",
        isCompleted: false,
      },
      {
        lectureId: "lec3",
        url: "https://youtu.be/y3OOaXrFy-Q?si=bVDNypIZdtIAyun1",
        title: "Continuous Integration (CI)",
        isCompleted: false,
      },
      {
        lectureId: "lec4",
        url: "https://youtu.be/y3OOaXrFy-Q?si=bVDNypIZdtIAyun1",
        title: "Continuous Delivery (CD)",
        isCompleted: false,
      },
      {
        lectureId: "lec5",
        url: "https://youtu.be/y3OOaXrFy-Q?si=bVDNypIZdtIAyun1",
        title: "Infrastructure as Code (IaC)",
        isCompleted: false,
      },
      {
        lectureId: "lec6",
        url: "https://youtu.be/y3OOaXrFy-Q?si=bVDNypIZdtIAyun1",
        title: "Monitoring and Logging",
        isCompleted: false,
      },
      {
        lectureId: "lec7",
        url: "https://youtu.be/y3OOaXrFy-Q?si=bVDNypIZdtIAyun1",
        title: "Containerization with Docker",
        isCompleted: false,
      },
      {
        lectureId: "lec8",
        url: "https://youtu.be/y3OOaXrFy-Q?si=bVDNypIZdtIAyun1",
        title: "Orchestration with Kubernetes",
        isCompleted: false,
      },
      {
        lectureId: "lec9",
        url: "https://youtu.be/y3OOaXrFy-Q?si=bVDNypIZdtIAyun1",
        title: "Security in DevOps",
        isCompleted: false,
      },
      {
        lectureId: "lec10",
        url: "https://youtu.be/y3OOaXrFy-Q?si=bVDNypIZdtIAyun1",
        title: "Future Trends in DevOps",
        isCompleted: false,
      },
    ],
  },
  {
    courseName: "Introduction to Web Development",
    instructor: "Sagar",
    description:
      "This course covers the fundamental concepts of web development, including HTML, CSS, and JavaScript. By learning web development, you can create interactive and responsive websites, enhancing your skills in front-end and back-end development. This course is essential for anyone looking to build a career in web development.",
    courseId: "course8",
    courseImg:
      "https://img.freepik.com/free-vector/online-courses-cartoon-advertising-web-page-with-students-sitting-books-pile-with-laptops-notebooks_1284-27827.jpg?size=626&ext=jpg&ga=GA1.1.77852075.1725111883&semt=ais_hybrid",
    isEnrolled: false,
    progress: 0,
    lectures: [
      {
        lectureId: "lec1",
        url: "https://youtu.be/y3OOaXrFy-Q?si=bVDNypIZdtIAyun1",
        title: "Introduction to Web Development",
        isCompleted: false,
      },
      {
        lectureId: "lec2",
        url: "https://youtu.be/y3OOaXrFy-Q?si=bVDNypIZdtIAyun1",
        title: "HTML Basics",
        isCompleted: false,
      },
      {
        lectureId: "lec3",
        url: "https://youtu.be/y3OOaXrFy-Q?si=bVDNypIZdtIAyun1",
        title: "CSS Fundamentals",
        isCompleted: false,
      },
      {
        lectureId: "lec4",
        url: "https://youtu.be/y3OOaXrFy-Q?si=bVDNypIZdtIAyun1",
        title: "JavaScript Essentials",
        isCompleted: false,
      },
      {
        lectureId: "lec5",
        url: "https://youtu.be/y3OOaXrFy-Q?si=bVDNypIZdtIAyun1",
        title: "Responsive Web Design",
        isCompleted: false,
      },
      {
        lectureId: "lec6",
        url: "https://youtu.be/y3OOaXrFy-Q?si=bVDNypIZdtIAyun1",
        title: "Introduction to Front-End Frameworks",
        isCompleted: false,
      },
      {
        lectureId: "lec7",
        url: "https://youtu.be/y3OOaXrFy-Q?si=bVDNypIZdtIAyun1",
        title: "Back-End Development Basics",
        isCompleted: false,
      },
      {
        lectureId: "lec8",
        url: "https://youtu.be/y3OOaXrFy-Q?si=bVDNypIZdtIAyun1",
        title: "Working with APIs",
        isCompleted: false,
      },
      {
        lectureId: "lec9",
        url: "https://youtu.be/y3OOaXrFy-Q?si=bVDNypIZdtIAyun1",
        title: "Web Development Tools and Best Practices",
        isCompleted: false,
      },
      {
        lectureId: "lec10",
        url: "https://youtu.be/y3OOaXrFy-Q?si=bVDNypIZdtIAyun1",
        title: "Deploying Your Website",
        isCompleted: false,
      },
    ],
  },
];
